#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# agnoster theme
autoload -Uz promptinit
promptinit
prompt agnoster

# foreman
fs()
{
  if [ -e Procfile.dev ]
  then
    foreman start -f Procfile.dev
  else
    foreman start
  fi
}
alias fs=fs

# neovim
alias vim="nvim"
export EDITOR="nvim"
export VISUAL="nvim"

# rbenv
export PATH="$HOME/.rbenv/shims:$PATH"
export PATH="/usr/local/opt/mongodb@3.0/bin:$PATH"
